stages:
  - build
  - gogen

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build and test:
  stage: build
  image: node:latest
  script:
  - apt-get -qq update
  - apt-get install -y jq
  - npm install
  - npm run compile
  - npm run test
  - for file in build/contracts/*.json; do jq '.abi' < "$file" > "${file%.json}.abi"; done
  - for file in build/contracts/*.json; do jq -r '.bytecode' < "$file" > "${file%.json}.bin"; done
  - mkdir build/contracts-flattened && for solfile in contracts/*.sol; do ./node_modules/.bin/truffle-flattener $solfile > build/contracts-flattened/${solfile##*/}; done
  - 'echo "Compiler: $(./node_modules/.bin/solcjs --version)" > build/contracts-flattened/README.md'
  artifacts:
    paths:
    - build/
    expire_in: 1 month

generate go packages:
  stage: gogen
  image: ethereum/client-go:alltools-v1.8.15
  script:
  - mkdir build/contracts-go
  - for file in contracts/*.sol; do f=$(basename -- ${file%.*}); abigen --abi "build/contracts/${f}.abi" --bin "build/contracts/${f}.bin" --out "build/contracts-go/${f}.go" --pkg contracts --type "${f}Contract"; done
  - cp -a build/contracts-flattened/. build/contracts-go/code
  artifacts:
    paths:
    - build/contracts-go
    expire_in: 1 month