language: node_js
sudo: required

node_js:
  - '10'

cache:
  directories:
    - node_modules

env:
  global:
    - ARTIFACTS_DIR=artifacts
    - ARTIFACT_NAME=reputation-contracts
    - ARTIFACT_EXT=zip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

install:
  - npm install

script:
  - npm run compile
  - npm run test

after_success:
  - for file in build/contracts/*.json; do jq '.abi' < "$file" > "${file%.json}.abi"; done
  - for file in build/contracts/*.json; do jq -r '.bytecode' < "$file" > "${file%.json}.bin"; done
  - mkdir ${ARTIFACTS_DIR} && for solfile in contracts/*.sol; do ./node_modules/.bin/truffle-flattener $solfile > ${ARTIFACTS_DIR}/${solfile##*/}; done
  - for file in contracts/*.sol; do f=$(basename -- ${file%.*}); cp "build/contracts/${f}.abi" ${ARTIFACTS_DIR}/; cp "build/contracts/${f}.bin" ${ARTIFACTS_DIR}/; done
  - 'echo "Compiler: $(./node_modules/.bin/solcjs --version)" > ${ARTIFACTS_DIR}/README.md'
  - 'echo "Contracts commit: ${TRAVIS_COMMIT}" >> ${ARTIFACTS_DIR}/README.md'
  - pushd ${ARTIFACTS_DIR}; zip -r ${ARTIFACT_NAME}.${ARTIFACT_EXT} .; popd
  - 'echo "Artifacts download URL: https://${ARTIFACTS_BUCKET}.s3.amazonaws.com/${TRAVIS_REPO_SLUG}/${TRAVIS_COMMIT}/${ARTIFACT_NAME}.${ARTIFACT_EXT}"'

addons:
  artifacts:
    s3_region: ${ARTIFACTS_S3_REGION}
    working_dir: ${ARTIFACTS_DIR}
    paths:
      - ${ARTIFACT_NAME}.${ARTIFACT_EXT}
    target_paths:
      - /${TRAVIS_REPO_SLUG}/${TRAVIS_COMMIT}

before_deploy:
  - cp ${ARTIFACTS_DIR}/${ARTIFACT_NAME}.${ARTIFACT_EXT} ${ARTIFACTS_DIR}/${ARTIFACT_NAME}-${TRAVIS_TAG}.${ARTIFACT_EXT}

deploy:
  provider: releases
  api_key:
    secure: xIhJUx8tzIgC5skh7gIWHz7NLHy6H5K/xrESLN1KqktTvFURKsFwLkAusKpce163g1DqvgeKYhd2rXcvsc8rqMBibLEA2FVJCbeAKcXjhxWXV+TlbarQdFIZSYKqNMwxu82YjfN16ITJO2MtSUepmax0tTPdtK03U6j1ZlNrlthJi62hLTc6vxEXL66FNY8JxtkTmY9jdqnHZhwMDefGRCFdK+5DqBSIIe+VEqeCGoYWQcZzkNZZk6nVO5/CzufpdfDPuWSX1fw+OchY0yI/txSJacDEqLmLXuW7WWRuT8CD7EdIzBT6FKUWfI5omGP04co4eR38WTuP3YnVr4T1O3ENw6QAPHgxCE2mmAFi4WYI88RVzHBtsNWnlXcsN+1gb9zj61yPntMQqZgOtvblJTqynBXcG2F1iWk6v8fhdPZudlkuAWdozON+IpxDYvktHpiRBRaZGeOuYzLL4Z3rbntrOYMYkr3JEbKq+lt3hpSS9TpDRtwXpLwX6bGuJQcZYouq6TG7R1SW1aLpP5VDH4FlENlNFchcDV5d2cNuuRNZ2dXzyt4BryW3K9dHeXxaY5ZF546k8tSLtH71nM0nZBNBxHfSjBnZYay5ja+HCPipIqx2hChwVe3M+evJevmtuPGh0MshtPJWf4lgb7xIbxT1mOWNARzIzFYUg5i43eE=
  file: ${ARTIFACTS_DIR}/${ARTIFACT_NAME}-${TRAVIS_TAG}.${ARTIFACT_EXT}
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
